services:
    postgres:
        image: postgres:17.5
        container_name: demo-postgres-dev
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: demo
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
    redis:
        image: redis:8.0.1
        container_name: demo-redis-dev
        ports:
            - "6379:6379"
        restart: unless-stopped

volumes:
    postgres-data:
